/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nested.includes.app;

import nested.includes.list.LinkedList;

import static nested.includes.utilities.StringUtils.join;
import static nested.includes.utilities.StringUtils.split;
import static nested.includes.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
